In [1]:
import numpy as np
import pandas as pdf
import pymysql
import sqlalchemy
import os

In [2]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine, text

In [4]:
file_path = os.path.join("Data", "clean", "healthcare_clean.csv")

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Columns list:", list(df.columns))

Dataset loaded successfully!
Rows: 54966
Columns: 17
Columns list: ['name', 'age', 'gender', 'blood_type', 'medical_condition', 'date_of_admission', 'doctor', 'hospital', 'insurance_provider', 'billing_amount', 'room_number', 'admission_type', 'discharge_date', 'medication', 'test_results', 'length_of_stay', 'age_group']

In [5]:
df.head()

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,length_of_stay,age_group
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,19-30
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,61-75
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,76+
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,19-30
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,31-45

In [6]:
df.tail()

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,length_of_stay,age_group
54961,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal,30,31-45
54962,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal,9,61-75
54963,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal,28,31-45
54964,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal,6,31-45
54965,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal,27,46-60

In [7]:
df.describe()

                age  billing_amount   room_number  length_of_stay
count  54966.000000    54966.000000  54966.000000    54966.000000
mean      51.535185    25544.306284    301.124404       15.499290
std       19.605661    14208.409711    115.223143        8.661471
min       13.000000    -2008.492140    101.000000        1.000000
25%       35.000000    13243.718641    202.000000        8.000000
50%       52.000000    25542.749145    302.000000       15.000000
75%       68.000000    37819.858159    401.000000       23.000000
max       89.000000    52764.276736    500.000000       30.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54966 entries, 0 to 54965
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                54966 non-null  object
 1   age                 54966 non-null  int64
 2   gender              54966 non-null  object
 3   blood_type          54966 non-null  object
 4   medical_condition   54966 non-null  object
 5   date_of_admission   54966 non-null  object
 6   doctor              54966 non-null  object
 7   hospital            54966 non-null  object
 8   insurance_provider  54966 non-null  object
 9   billing_amount      54966 non-null  float64
 10  room_number         54966 non-null  int64
 11  admission_type      54966 non-null  object
 12  discharge_date      54966 non-null  object
 13  medication          54966 non-null  object
 14  test_results        54966 non-null  object
 15  length_of_stay      54966 non-null  int64
 16  age_group           54966 non-null  object
dtypes: float64(1), int64(3), object(13)
memory usage: 7.1+ MB

In [9]:
print("Missing values:")
print(df.isnull().sum().sum())

print("Duplicate rows:")
print(df.duplicated().sum())

Missing values:
0
Duplicate rows:
0

In [16]:
MYSQL_USER = "root"
MYSQL_PASSWORD = "sjbarad777"
MYSQL_HOST = "localhost"
MYSQL_PORT = 3306
MYSQL_DATABASE = "healthcare_db"

In [11]:
engine = create_engine(
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}"
    f"@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"
)

print("SQLAlchemy engine created successfully!")

SQLAlchemy engine created successfully!

In [12]:
try:
    with engine.connect() as connection:
        result = connection.execute(text("SELECT 1"))
        print("MySQL connection successful! ✅")
except Exception as e:
    print("MySQL connection failed ❌")
    print(e)

MySQL connection failed ❌
(pymysql.err.OperationalError) (1049, "Unknown database 'healthcare_db'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [17]:
from sqlalchemy import table, column
from sqlalchemy.dialects.mysql import insert

In [21]:
from sqlalchemy import create_engine, text

MYSQL_USER = "root"
MYSQL_PASSWORD = "sjbarad777"
MYSQL_HOST = "localhost"
MYSQL_PORT = 3306
MYSQL_DATABASE = "healthcare_db"

engine = create_engine(
    f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}"
    f"@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}"
)

In [22]:
try:
    with engine.connect() as connection:
        result = connection.execute(text("SELECT 1"))
        print("MySQL connection successful! ✅")

except Exception as e:
    print("MySQL connection failed ❌")
    print(e)

MySQL connection successful! ✅

In [23]:
table_name = "healthcare_records"

df.to_sql(
    name=table_name,
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded into MySQL successfully! ✅")

Data loaded into MySQL successfully! ✅

In [24]:
with engine.connect() as connection:
    tables = connection.execute(
        text("SHOW TABLES")
    ).fetchall()

print(tables)

[('healthcare_records',)]

In [25]:
query = """
SELECT COUNT(*) AS total_records
FROM healthcare_records
"""

result = pd.read_sql(query, engine)

result

   total_records
0          54966

In [26]:
print("Python rows :", len(df))
print("MySQL rows  :", result["total_records"].iloc[0])

Python rows : 54966
MySQL rows  : 54966

In [27]:
query = """
SELECT *
FROM healthcare_records
LIMIT 10
"""

mysql_sample = pd.read_sql(query, engine)

mysql_sample

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,length_of_stay,age_group
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,19-30
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,61-75
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,76+
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,19-30
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,31-45
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal,4,31-45
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive,12,19-30
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive,10,19-30
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal,13,76+
9,ChRISTopher BerG,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.631062,249,Elective,2021-06-22,Paracetamol,Inconclusive,30,46-60

In [28]:
query = """
SELECT
    COUNT(*) AS total_admissions,
    ROUND(SUM(billing_amount), 2) AS total_billing,
    ROUND(AVG(billing_amount), 2) AS average_billing,
    ROUND(AVG(age), 2) AS average_age,
    ROUND(AVG(length_of_stay), 2) AS average_length_of_stay
FROM healthcare_records
"""

kpi = pd.read_sql(query, engine)

kpi

,total_admissions,total_billing,average_billing,average_age,average_length_of_stay
0,54966,1.404068e+09,25544.31,51.54,15.5

In [29]:
# medical conndition analysis 
query = """
SELECT
    medical_condition,
    COUNT(*) AS admissions,
    ROUND(SUM(billing_amount), 2) AS total_billing,
    ROUND(AVG(billing_amount), 2) AS average_billing,
    ROUND(AVG(length_of_stay), 2) AS average_length_of_stay
FROM healthcare_records
GROUP BY medical_condition
ORDER BY admissions DESC
"""

condition_analysis = pd.read_sql(query, engine)

condition_analysis

,medical_condition,admissions,total_billing,average_billing,average_length_of_stay
0,Arthritis,9218,2.351676e+08,25511.78,15.50
1,Diabetes,9216,2.364870e+08,25660.48,15.43
2,Hypertension,9151,2.333785e+08,25503.06,15.44
3,Obesity,9146,2.360067e+08,25804.36,15.45
4,Cancer,9140,2.298922e+08,25152.32,15.50
5,Asthma,9095,2.331363e+08,25633.46,15.68

In [30]:
query = """
SELECT
    hospital,
    COUNT(*) AS admissions,
    ROUND(SUM(billing_amount), 2) AS total_billing,
    ROUND(AVG(billing_amount), 2) AS average_billing,
    ROUND(AVG(length_of_stay), 2) AS average_length_of_stay
FROM healthcare_records
GROUP BY hospital
ORDER BY total_billing DESC
LIMIT 20
"""

hospital_analysis = pd.read_sql(query, engine)

hospital_analysis

,hospital,admissions,total_billing,average_billing,average_length_of_stay
0,Johnson PLC,37,1081477.31,29229.12,16.14
1,LLC Smith,44,1030189.87,23413.41,15.57
2,Smith PLC,36,1029424.45,28595.12,17.64
3,Ltd Smith,39,1003365.53,25727.32,16.51
4,Smith Ltd,37,970035.87,26217.19,15.14
5,Johnson Inc,34,934310.73,27479.73,14.53
6,Group Smith,32,902975.79,28217.99,16.31
7,Inc Brown,27,877961.31,32517.09,13.56
8,LLC Johnson,30,816438.35,27214.61,17.03
9,Smith Group,36,806631.29,22406.42,17.00
10,Inc Jones,25,804936.44,32197.46,15.00
11,Brown Inc,28,790322.57,28225.81,12.75
12,Smith Inc,33,772256.50,23401.71,15.39
13,Inc Smith,27,770747.93,28546.22,14.04
14,Johnson Group,27,734430.55,27201.13,16.33
15,PLC Williams,30,731847.96,24394.93,16.13
16,Smith LLC,32,731683.65,22865.11,16.09
17,Johnson Ltd,21,729445.37,34735.49,15.29
18,Group Johnson,26,722079.92,27772.30,17.58
19,Inc Williams,23,716737.47,31162.50,19.04

In [31]:
query = """
SELECT
    insurance_provider,
    COUNT(*) AS admissions,
    ROUND(SUM(billing_amount), 2) AS total_billing,
    ROUND(AVG(billing_amount), 2) AS average_billing
FROM healthcare_records
GROUP BY insurance_provider
ORDER BY total_billing DESC
"""

insurance_analysis = pd.read_sql(query, engine)

insurance_analysis

  insurance_provider  admissions  total_billing  average_billing
0              Cigna       11139   2.843341e+08         25526.00
1           Medicare       11039   2.829110e+08         25628.32
2         Blue Cross       10952   2.804091e+08         25603.46
3   UnitedHealthcare       11014   2.799154e+08         25414.51
4              Aetna       10822   2.764987e+08         25549.69

In [32]:
query = """
SELECT
    admission_type,
    COUNT(*) AS admissions,
    ROUND(SUM(billing_amount), 2) AS total_billing,
    ROUND(AVG(billing_amount), 2) AS average_billing,
    ROUND(AVG(length_of_stay), 2) AS average_length_of_stay
FROM healthcare_records
GROUP BY admission_type
ORDER BY admissions DESC
"""

admission_analysis = pd.read_sql(query, engine)

admission_analysis

,admission_type,admissions,total_billing,average_billing,average_length_of_stay
0,Elective,18473,4.731331e+08,25612.14,15.51
1,Urgent,18391,4.692378e+08,25514.53,15.40
2,Emergency,18102,4.616975e+08,25505.33,15.58

In [33]:
query = """
SELECT
    age_group,
    COUNT(*) AS admissions,
    ROUND(SUM(billing_amount), 2) AS total_billing,
    ROUND(AVG(billing_amount), 2) AS average_billing,
    ROUND(AVG(length_of_stay), 2) AS average_length_of_stay
FROM healthcare_records
GROUP BY age_group
ORDER BY admissions DESC
"""

age_analysis = pd.read_sql(query, engine)

age_analysis

,age_group,admissions,total_billing,average_billing,average_length_of_stay
0,46-60,12273,3.129290e+08,25497.35,15.59
1,31-45,12116,3.103985e+08,25618.89,15.32
2,61-75,12098,3.082748e+08,25481.47,15.60
3,19-30,9519,2.430218e+08,25530.18,15.46
4,76+,8074,2.057471e+08,25482.67,15.52
5,0-18,886,2.369721e+07,26746.28,15.50

In [34]:
query = """
SELECT
    ROUND(MIN(billing_amount), 2) AS minimum_billing,
    ROUND(MAX(billing_amount), 2) AS maximum_billing,
    ROUND(AVG(billing_amount), 2) AS average_billing,
    ROUND(SUM(billing_amount), 2) AS total_billing
FROM healthcare_records
"""

billing_analysis = pd.read_sql(query, engine)

billing_analysis

   minimum_billing  maximum_billing  average_billing  total_billing
0         -2008.49         52764.28         25544.31   1.404068e+09

In [35]:
query = """
SELECT
    MIN(length_of_stay) AS minimum_stay,
    MAX(length_of_stay) AS maximum_stay,
    ROUND(AVG(length_of_stay), 2) AS average_stay
FROM healthcare_records
"""

los_analysis = pd.read_sql(query, engine)

los_analysis

   minimum_stay  maximum_stay  average_stay
0             1            30          15.5

In [36]:
query = """
SELECT
    YEAR(date_of_admission) AS admission_year,
    MONTH(date_of_admission) AS admission_month,
    COUNT(*) AS admissions,
    ROUND(SUM(billing_amount), 2) AS total_billing,
    ROUND(AVG(billing_amount), 2) AS average_billing
FROM healthcare_records
GROUP BY
    YEAR(date_of_admission),
    MONTH(date_of_admission)
ORDER BY
    admission_year,
    admission_month
"""

monthly_analysis = pd.read_sql(query, engine)

monthly_analysis

,admission_year,admission_month,admissions,total_billing,average_billing
0,2019,5,677,17403451.24,25706.72
1,2019,6,899,23613799.97,26266.74
2,2019,7,951,24632284.83,25901.46
3,2019,8,985,24997039.11,25377.70
4,2019,9,924,23021967.21,24915.55
...,...,...,...,...,...
56,2024,1,903,23330536.27,25836.70
57,2024,2,869,22228658.61,25579.58
58,2024,3,902,22777966.17,25252.73
59,2024,4,941,23407751.98,24875.40
60,2024,5,212,5398559.42,25464.90

In [39]:
# month-over-month growth analysis
query = """
SELECT
    m.month,
    ROUND(m.total_billing, 2) AS total_billing,
    ROUND(p.total_billing, 2) AS previous_month_billing,
    ROUND(
        ((m.total_billing - COALESCE(p.total_billing, 0))
        / NULLIF(COALESCE(p.total_billing, 0), 0)) * 100,
        2
    ) AS mom_growth_pct
FROM (
    SELECT
        DATE_FORMAT(date_of_admission, '%Y-%m') AS month,
        SUM(billing_amount) AS total_billing
    FROM healthcare_records
    GROUP BY DATE_FORMAT(date_of_admission, '%Y-%m')
) AS m
LEFT JOIN (
    SELECT
        DATE_FORMAT(DATE_SUB(date_of_admission, INTERVAL 1 MONTH), '%Y-%m') AS month,
        SUM(billing_amount) AS total_billing
    FROM healthcare_records
    GROUP BY DATE_FORMAT(DATE_SUB(date_of_admission, INTERVAL 1 MONTH), '%Y-%m')
) AS p
    ON p.month = m.month
ORDER BY m.month
"""

try:
    mom_analysis = pd.read_sql(query, engine)
    mom_analysis
except Exception as e:
    print("Month-over-month analysis failed ❌")
    print(e)

Month-over-month analysis failed ❌
unsupported format character 'Y' (0x59) at index 346

In [40]:
validation_query = """
SELECT
    COUNT(*) AS total_records,
    COUNT(DISTINCT hospital) AS hospitals,
    COUNT(DISTINCT doctor) AS doctors,
    COUNT(DISTINCT medical_condition) AS medical_conditions,
    COUNT(DISTINCT insurance_provider) AS insurance_providers
FROM healthcare_records
"""

validation = pd.read_sql(validation_query, engine)

validation

   total_records  hospitals  doctors  medical_conditions  insurance_providers
0          54966      39876    40341                   6                    5

In [41]:
mysql_count = pd.read_sql(
    "SELECT COUNT(*) AS count FROM healthcare_records",
    engine
)["count"].iloc[0]

python_count = len(df)

print("Python records :", python_count)
print("MySQL records  :", mysql_count)

if python_count == mysql_count:
    print("Validation PASSED ✅")
else:
    print("Validation FAILED ❌")

Python records : 54966
MySQL records  : 54966
Validation PASSED ✅