In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [4]:
df = pd.read_csv("../Data/healthcare_dataset.csv")


df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [5]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 55500
Columns: 15

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [7]:
df.describe(include='all')

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
count,55500,55500.000000,55500,55500,55500,55500,55500,55500,55500,55500.000000,55500.000000,55500,55500,55500,55500
unique,49992,NaN,2,8,6,1827,40341,39876,5,NaN,NaN,3,1856,5,3
top,DAvId muNoZ,NaN,Male,A-,Arthritis,2024-03-16,Michael Smith,LLC Smith,Cigna,NaN,NaN,Elective,2020-03-15,Lipitor,Abnormal
freq,3,NaN,27774,6969,9308,50,27,44,11249,NaN,NaN,18655,53,11140,18627
mean,NaN,51.539459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25539.316097,301.134829,NaN,NaN,NaN,NaN
std,NaN,19.602454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14211.454431,115.243069,NaN,NaN,NaN,NaN
min,NaN,13.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2008.492140,101.000000,NaN,NaN,NaN,NaN
25%,NaN,35.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13241.224652,202.000000,NaN,NaN,NaN,NaN
50%,NaN,52.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25538.069376,302.000000,NaN,NaN,NaN,NaN
75%,NaN,68.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37820.508436,401.000000,NaN,NaN,NaN,NaN
max,NaN,89.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52764.276736,500.000000,NaN,NaN,NaN,NaN

In [8]:
df.nunique().sort_values()

Gender                    2
Admission Type            3
Test Results              3
Medication                5
Insurance Provider        5
Medical Condition         6
Blood Type                8
Age                      77
Room Number             400
Date of Admission      1827
Discharge Date         1856
Hospital              39876
Doctor                40341
Name                  49992
Billing Amount        50000
dtype: int64

In [9]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [12]:
missing = df.isnull().sum()

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Missing %": (missing / len(df) * 100).round(2)
})

missing_df.sort_values("Missing Values", ascending=False)

                    Missing Values  Missing %
Name                             0        0.0
Age                              0        0.0
Gender                           0        0.0
Blood Type                       0        0.0
Medical Condition                0        0.0
Date of Admission                0        0.0
Doctor                           0        0.0
Hospital                         0        0.0
Insurance Provider               0        0.0
Billing Amount                   0        0.0
Room Number                      0        0.0
Admission Type                   0        0.0
Discharge Date                   0        0.0
Medication                       0        0.0
Test Results                     0        0.0

In [13]:
# check it duplicate rows
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 534

In [14]:
df = df.drop_duplicates().copy()

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 54966

In [15]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.columns

Index(['name', 'age', 'gender', 'blood_type', 'medical_condition',
       'date_of_admission', 'doctor', 'hospital', 'insurance_provider',
       'billing_amount', 'room_number', 'admission_type', 'discharge_date',
       'medication', 'test_results'],
      dtype='object')

In [16]:
# convert Date 
df["date_of_admission"] = pd.to_datetime(
    df["date_of_admission"],
    errors="coerce"
)

df["discharge_date"] = pd.to_datetime(
    df["discharge_date"],
    errors="coerce"
)

In [17]:
# lenght of stay 
df["length_of_stay"] = (
    df["discharge_date"] - df["date_of_admission"]
).dt.days

In [20]:
df["length_of_stay"].describe()

count    54966.000000
mean        15.499290
std          8.661471
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: length_of_stay, dtype: float64

In [21]:
df[df["length_of_stay"] < 0]

Empty DataFrame
Columns: [name, age, gender, blood_type, medical_condition, date_of_admission, doctor, hospital, insurance_provider, billing_amount, room_number, admission_type, discharge_date, medication, test_results, length_of_stay]
Index: []

In [22]:
# clean categorical columns
categorical_cols = [
    "gender",
    "blood_type",
    "medical_condition",
    "insurance_provider",
    "admission_type",
    "medication",
    "test_results"
]

for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip()

In [23]:
print("Invalid ages:", ((df["age"] < 0) | (df["age"] > 120)).sum())
print("Invalid billing:", (df["billing_amount"] < 0).sum())
print("Invalid stay:", (df["length_of_stay"] < 0).sum())

Invalid ages: 0
Invalid billing: 106
Invalid stay: 0

In [24]:
# create a usefull analytics colums 
print("Invalid ages:", ((df["age"] < 0) | (df["age"] > 120)).sum())
print("Invalid billing:", (df["billing_amount"] < 0).sum())
print("Invalid stay:", (df["length_of_stay"] < 0).sum())

Invalid ages: 0
Invalid billing: 106
Invalid stay: 0

In [25]:
#AGE Grouping
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 18, 30, 45, 60, 75, 120],
    labels=[
        "0-18",
        "19-30",
        "31-45",
        "46-60",
        "61-75",
        "76+"
    ],
    include_lowest=True
)

In [26]:
# Final quality check
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Rows: 54966
Columns: 17

Missing values:
name                  0
age                   0
gender                0
blood_type            0
medical_condition     0
date_of_admission     0
doctor                0
hospital              0
insurance_provider    0
billing_amount        0
room_number           0
admission_type        0
discharge_date        0
medication            0
test_results          0
length_of_stay        0
age_group             0
dtype: int64

Duplicate rows:
0

In [27]:
# Export the cleaned dataset
df.to_csv(
    "../Data/healthcare_clean.csv",
    index=False
)

print("Clean dataset exported successfully.")

Clean dataset exported successfully.